# See https://pre-commit.com  and https://madewithml.com/courses/mlops/pre-commit/ for more information
# See https://pre-commit.com/hooks.html for more hooks

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: check-yaml
        exclude: "mkdocs.yml|.github-ci.yml"
      - id: check-added-large-files
        args: ["--maxkb=1000"]
        exclude: '.*\.ipynb$|.*\.csv|.*\.json|.*\.tsv|.*\.pdf'
      - id: check-ast
      - id: check-json
      - id: check-merge-conflict
      - id: detect-private-key
      - id: end-of-file-fixer

  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile=black"]
        files: .

  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black
        args: []
        files: .


  - repo: https://github.com/pycqa/flake8
    # Refer to these links for more error codes: https://pycodestyle.pycqa.org/en/latest/intro.html#error-codes
    # and https://flake8.pycqa.org/en/latest/user/error-codes.html
    rev: 3.9.2
    hooks:
      - id: flake8
        args: ['--ignore=E402,E501,E741,E266,W503,E203,E265,F523']
        files: .


  - repo: https://github.com/pylint-dev/pylint
    rev: pylint-2.8.0
    hooks:
      - id: pylint
        args: ['--fail-under', '7.0']